### PR TITLE
Parameterize header.frame_id and child_frame_id

### PR DESCRIPTION
**Pull request by ajayjain**
Allow the Odometry message's header.frame_id and child_frame_id to be configured with a rosparam.

### CODE REVIEW

**Comment by ajayjain** [comment]
I have multiple Husky robots running on the same network with namespaced/prefixed frames. To visualize Odometry in RViz, I had written a node that relays these Odometry messages to a new topic and changes the frame ids, but this should be parameterized in the original node.

**Comment by mikepurvis** [comment]
This looks good to me, but should the frame_id really be `odom_combined`? I would have thought just `odom`, and then the localizer publishes `odom_combined`.

@pmukherj Should this be changed for Indigo?

**Comment by pmukherj** [comment]
Yea, you are right. It shouldn't be odom_combined. Just 'odom' or 'wheel_odom' is better. 
As for indigo, that should be @abencz making the merge call.

**Comment by ajayjain** [comment]
Updated. That was my original thought as well, but I had robot_pose_ekf supplying an robot_x/odom_combined to robot_x/base_footprint transform anyway with encoder data.

**Comment by mikepurvis** [comment]
Because it's now a breaking change, it should probably target indigo.

@abencz On you to merge this.

**Comment by paulbovbel** [comment]
Moving to ros_control in indigo

**Pull request closed without merging**
